name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token : ${{ secrets.GH_PAT }}
      
      - name: Get node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Configure Git
        run: git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "ssh://git@github.com/"

      - name: Install dependencies
        run: npm ci

      - name: Download circuits
        run: ./dl_circuits.sh

      - name: Run tests
        run: npm run test
