name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Configure Git
        run: git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "ssh://git@github.com/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Download circuits
        run: ./dl_circuits.sh

      # To check if merge conflicts were resolved correctly
      - name: Validate JSON files
        run: |
          find ignition/deployments -name "*.json" -print0 | xargs -0 -n1 jq empty

      - name: Run tests
        run: npm run test
