name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      id-token: write
      contents: write
      packages: read
    strategy:
      matrix:
        node: [ 20 ]
    steps:
      - name: Set github url and credentials
        run: |
          git config --global --replace-all url."https://${GH_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"    
          git config --global --add url."https://${GH_TOKEN}:x-oauth-basic@github.com/".insteadOf "ssh://git@github.com/"
          git config --global --add url."https://${GH_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: Print git config list
        run: git config --list
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }} # https://github.com/actions/setup-node#matrix-testing
          registry-url: 'https://registry.npmjs.org'
      - name: Replace GitHub URL with token
        run: |
          sed -i "s|https://github.com/|https://${GH_TOKEN}:x-oauth-basic@github.com/|g" package.json
      - name: Confirm replacement
        run: |
          grep passport-utils package.json
      - name: Print package.json
        run: cat package.json
      - name: Install node_modules
        run: npm install
      - name: Download circuits
        run: ./dl_circuit.sh
      - name: Test contracts
        run: npm run test
