name: Security Scan
on:  # yamllint disable-line rule:truthy
  push:
  workflow_call:
  workflow_dispatch: {}

jobs:
  solhint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token : ${{ secrets.GH_PAT }}

      - name: Get node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure Git
        run: git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "ssh://git@github.com/"

      - name: Install dependencies
        run: npm ci

      - name: Solhint contracts
        run: npx solhint "contracts/**/*.sol"

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token : ${{ secrets.GH_PAT }}

      - name: Get node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure Git
        run: git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "ssh://git@github.com/"

      - name: Install dependencies
        run: npm ci

      - name: Download circuits
        run: ./dl_circuits.sh

      - run: npx hardhat compile

      - name: solidity-coverage
        run: npx hardhat coverage

