name: Security Scan
on:  # yamllint disable-line rule:truthy
  push:
  workflow_call:
  workflow_dispatch: {}

jobs:
  solhint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: Get node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Replace GitHub URL with token
        run: |
          sed -i "s|https://github.com/|https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/|g" package.json
      - name: Confirm replacement
        run: |
          grep passport-utils package.json
      - name: Print package.json
        run: cat package.json
      - name: Set github url and credentials
        run: |
          git config --global --replace-all url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "git@github.com:"          
          git config --global --add url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"
          git config --global --add url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - run: npm ci
      - run: npx solhint "contracts/**/*.sol"

  coverage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: Get node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Replace GitHub URL with token
        run: |
          sed -i "s|https://github.com/|https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/|g" package.json
      - name: Confirm replacement
        run: |
          grep passport-utils package.json
      - name: Print package.json
        run: cat package.json
      - name: Set github url and credentials
        run: |
          git config --global --replace-all url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "git@github.com:"          
          git config --global --add url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"
          git config --global --add url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - run: npm ci
      - run: npx hardhat compile
      - name: Download circuits
        run: ./dl_circuit.sh
      - name: solidity-coverage
        run: npx hardhat coverage
      - name: coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
