name: Security Scan
on:  # yamllint disable-line rule:truthy
  push:
  workflow_call:
  workflow_dispatch: {}

jobs:
  solhint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token : ${{ secrets.GH_PAT }}

      - name: Get node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure Git
        run: git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "ssh://git@github.com/"

      - name: Install dependencies
        run: npm ci

      - name: Solhint contracts
        run: npx solhint "contracts/**/*.sol"

  # coverage:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         token : ${{ secrets.GH_PAT }}

  #     - name: Get node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20

  #     - name: Configure Git
  #       run: git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "ssh://git@github.com/"

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Download circuits
  #       run: ./dl_circuits.sh

  #     - run: npx hardhat compile

  #     - name: solidity-coverage
  #       env:
  #         NODE_OPTIONS: "--max_old_space_size=16384" 
  #       run: npx hardhat coverage

